(require 'clips-mode)
(require 'clojure-mode)
(require 'coffee-mode)
(load "ess-autoloads")
(require 'ess-site)
(require 'groovy-mode)
(require 'haskell-mode)
;; (require 'jess-mode)
(require 'js2-mode)
(require 'sml-mode)
(require 'tuareg)

(require 'pretty-mode)
(global-pretty-mode t)
